### ISSUE TITLE
Upstream-servers don't work, ends up in webroot instead

### ISSUE THREAD

**Issue by ScuttleSE** [nickjj/ansible-nginx#13]
Got a site defined like this:

```
  example.se:
    domains: ['example.se', 'www.example.se']
    default_server: False
    upstreams:
      - name: 'example'
        servers: ['hostname_of_internal_server:80']
```

When accessing it I end up with the default nginx-page from /usr/share/nginx/html instead of being forwarded to my upstream-server
